// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/commands.proto

package commands

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MIGletMessage represents messages sent from MIGlet to Controller
type MIGletMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*MIGletMessage_Connect
	//	*MIGletMessage_CommandAck
	//	*MIGletMessage_Event
	//	*MIGletMessage_Heartbeat
	//	*MIGletMessage_Error
	Message       isMIGletMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MIGletMessage) Reset() {
	*x = MIGletMessage{}
	mi := &file_proto_commands_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MIGletMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MIGletMessage) ProtoMessage() {}

func (x *MIGletMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commands_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MIGletMessage.ProtoReflect.Descriptor instead.
func (*MIGletMessage) Descriptor() ([]byte, []int) {
	return file_proto_commands_proto_rawDescGZIP(), []int{0}
}

func (x *MIGletMessage) GetMessage() isMIGletMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *MIGletMessage) GetConnect() *ConnectRequest {
	if x != nil {
		if x, ok := x.Message.(*MIGletMessage_Connect); ok {
			return x.Connect
		}
	}
	return nil
}

func (x *MIGletMessage) GetCommandAck() *CommandAck {
	if x != nil {
		if x, ok := x.Message.(*MIGletMessage_CommandAck); ok {
			return x.CommandAck
		}
	}
	return nil
}

func (x *MIGletMessage) GetEvent() *EventNotification {
	if x != nil {
		if x, ok := x.Message.(*MIGletMessage_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *MIGletMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Message.(*MIGletMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *MIGletMessage) GetError() *ErrorNotification {
	if x != nil {
		if x, ok := x.Message.(*MIGletMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isMIGletMessage_Message interface {
	isMIGletMessage_Message()
}

type MIGletMessage_Connect struct {
	// Initial connection message
	Connect *ConnectRequest `protobuf:"bytes,1,opt,name=connect,proto3,oneof"`
}

type MIGletMessage_CommandAck struct {
	// Command acknowledgment
	CommandAck *CommandAck `protobuf:"bytes,2,opt,name=command_ack,json=commandAck,proto3,oneof"`
}

type MIGletMessage_Event struct {
	// Event notification (VM started, job started, etc.)
	Event *EventNotification `protobuf:"bytes,3,opt,name=event,proto3,oneof"`
}

type MIGletMessage_Heartbeat struct {
	// Heartbeat with metrics
	Heartbeat *Heartbeat `protobuf:"bytes,4,opt,name=heartbeat,proto3,oneof"`
}

type MIGletMessage_Error struct {
	// Error notification
	Error *ErrorNotification `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

func (*MIGletMessage_Connect) isMIGletMessage_Message() {}

func (*MIGletMessage_CommandAck) isMIGletMessage_Message() {}

func (*MIGletMessage_Event) isMIGletMessage_Message() {}

func (*MIGletMessage_Heartbeat) isMIGletMessage_Message() {}

func (*MIGletMessage_Error) isMIGletMessage_Message() {}

// ControllerMessage represents messages sent from Controller to MIGlet
type ControllerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ControllerMessage_ConnectAck
	//	*ControllerMessage_Command
	//	*ControllerMessage_Error
	Message       isControllerMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerMessage) Reset() {
	*x = ControllerMessage{}
	mi := &file_proto_commands_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerMessage) ProtoMessage() {}

func (x *ControllerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commands_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerMessage.ProtoReflect.Descriptor instead.
func (*ControllerMessage) Descriptor() ([]byte, []int) {
	return file_proto_commands_proto_rawDescGZIP(), []int{1}
}

func (x *ControllerMessage) GetMessage() isControllerMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ControllerMessage) GetConnectAck() *ConnectAck {
	if x != nil {
		if x, ok := x.Message.(*ControllerMessage_ConnectAck); ok {
			return x.ConnectAck
		}
	}
	return nil
}

func (x *ControllerMessage) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Message.(*ControllerMessage_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *ControllerMessage) GetError() *ErrorNotification {
	if x != nil {
		if x, ok := x.Message.(*ControllerMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isControllerMessage_Message interface {
	isControllerMessage_Message()
}

type ControllerMessage_ConnectAck struct {
	// Connection acknowledgment
	ConnectAck *ConnectAck `protobuf:"bytes,1,opt,name=connect_ack,json=connectAck,proto3,oneof"`
}

type ControllerMessage_Command struct {
	// Command to execute
	Command *Command `protobuf:"bytes,2,opt,name=command,proto3,oneof"`
}

type ControllerMessage_Error struct {
	// Error notification
	Error *ErrorNotification `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*ControllerMessage_ConnectAck) isControllerMessage_Message() {}

func (*ControllerMessage_Command) isControllerMessage_Message() {}

func (*ControllerMessage_Error) isControllerMessage_Message() {}

// ConnectRequest is sent by MIGlet when establishing connection
type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	PoolId        string                 `protobuf:"bytes,2,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_proto_commands_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commands_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_proto_commands_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *ConnectRequest) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

func (x *ConnectRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *ConnectRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// ConnectAck is sent by Controller to acknowledge connection
type ConnectAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ServerVersion string                 `protobuf:"bytes,3,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectAck) Reset() {
	*x = ConnectAck{}
	mi := &file_proto_commands_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectAck) ProtoMessage() {}

func (x *ConnectAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commands_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectAck.ProtoReflect.Descriptor instead.
func (*ConnectAck) Descriptor() ([]byte, []int) {
	return file_proto_commands_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ConnectAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConnectAck) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

// Command represents a command from Controller to MIGlet
type Command struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type              string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // register_runner, drain, shutdown, update_config, set_log_level
	StringParams      map[string]string      `protobuf:"bytes,3,rep,name=string_params,json=stringParams,proto3" json:"string_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IntParams         map[string]int64       `protobuf:"bytes,4,rep,name=int_params,json=intParams,proto3" json:"int_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	BoolParams        map[string]bool        `protobuf:"bytes,5,rep,name=bool_params,json=boolParams,proto3" json:"bool_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	StringArrayParams []string               `protobuf:"bytes,6,rep,name=string_array_params,json=stringArrayParams,proto3" json:"string_array_params,omitempty"` // For labels, etc.
	CreatedAt         int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                          // Unix timestamp
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_proto_commands_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commands_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_proto_commands_proto_rawDescGZIP(), []int{4}
}

func (x *Command) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Command) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Command) GetStringParams() map[string]string {
	if x != nil {
		return x.StringParams
	}
	return nil
}

func (x *Command) GetIntParams() map[string]int64 {
	if x != nil {
		return x.IntParams
	}
	return nil
}

func (x *Command) GetBoolParams() map[string]bool {
	if x != nil {
		return x.BoolParams
	}
	return nil
}

func (x *Command) GetStringArrayParams() []string {
	if x != nil {
		return x.StringArrayParams
	}
	return nil
}

func (x *Command) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// CommandAck is sent by MIGlet to acknowledge command processing
type CommandAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Result        map[string]string      `protobuf:"bytes,4,rep,name=result,proto3" json:"result,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Optional result data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandAck) Reset() {
	*x = CommandAck{}
	mi := &file_proto_commands_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandAck) ProtoMessage() {}

func (x *CommandAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commands_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandAck.ProtoReflect.Descriptor instead.
func (*CommandAck) Descriptor() ([]byte, []int) {
	return file_proto_commands_proto_rawDescGZIP(), []int{5}
}

func (x *CommandAck) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommandAck) GetResult() map[string]string {
	if x != nil {
		return x.Result
	}
	return nil
}

// EventNotification represents events from MIGlet
type EventNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // vm_started, runner_registered, job_started, job_completed, etc.
	VmId          string                 `protobuf:"bytes,2,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	PoolId        string                 `protobuf:"bytes,3,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,4,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Data          map[string]string      `protobuf:"bytes,5,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Event-specific data
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventNotification) Reset() {
	*x = EventNotification{}
	mi := &file_proto_commands_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventNotification) ProtoMessage() {}

func (x *EventNotification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commands_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventNotification.ProtoReflect.Descriptor instead.
func (*EventNotification) Descriptor() ([]byte, []int) {
	return file_proto_commands_proto_rawDescGZIP(), []int{6}
}

func (x *EventNotification) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventNotification) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *EventNotification) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

func (x *EventNotification) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *EventNotification) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EventNotification) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Heartbeat contains VM health and runner state
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	PoolId        string                 `protobuf:"bytes,2,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Health        *VMHealth              `protobuf:"bytes,4,opt,name=health,proto3" json:"health,omitempty"`
	RunnerState   *RunnerState           `protobuf:"bytes,5,opt,name=runner_state,json=runnerState,proto3" json:"runner_state,omitempty"`
	CurrentJob    *JobInfo               `protobuf:"bytes,6,opt,name=current_job,json=currentJob,proto3" json:"current_job,omitempty"`
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MigletState   string                 `protobuf:"bytes,8,opt,name=miglet_state,json=migletState,proto3" json:"miglet_state,omitempty"` // MIGlet state machine state: initializing, connecting, ready, registering_runner, idle, job_running, draining, shutting_down, error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_commands_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commands_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_commands_proto_rawDescGZIP(), []int{7}
}

func (x *Heartbeat) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *Heartbeat) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

func (x *Heartbeat) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *Heartbeat) GetHealth() *VMHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

func (x *Heartbeat) GetRunnerState() *RunnerState {
	if x != nil {
		return x.RunnerState
	}
	return nil
}

func (x *Heartbeat) GetCurrentJob() *JobInfo {
	if x != nil {
		return x.CurrentJob
	}
	return nil
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Heartbeat) GetMigletState() string {
	if x != nil {
		return x.MigletState
	}
	return ""
}

// VMHealth contains VM metrics
type VMHealth struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CpuUsagePercent    float64                `protobuf:"fixed64,1,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	MemoryUsagePercent float64                `protobuf:"fixed64,2,opt,name=memory_usage_percent,json=memoryUsagePercent,proto3" json:"memory_usage_percent,omitempty"`
	DiskUsagePercent   float64                `protobuf:"fixed64,3,opt,name=disk_usage_percent,json=diskUsagePercent,proto3" json:"disk_usage_percent,omitempty"`
	MemoryTotalBytes   int64                  `protobuf:"varint,4,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	MemoryUsedBytes    int64                  `protobuf:"varint,5,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	DiskTotalBytes     int64                  `protobuf:"varint,6,opt,name=disk_total_bytes,json=diskTotalBytes,proto3" json:"disk_total_bytes,omitempty"`
	DiskUsedBytes      int64                  `protobuf:"varint,7,opt,name=disk_used_bytes,json=diskUsedBytes,proto3" json:"disk_used_bytes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *VMHealth) Reset() {
	*x = VMHealth{}
	mi := &file_proto_commands_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMHealth) ProtoMessage() {}

func (x *VMHealth) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commands_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMHealth.ProtoReflect.Descriptor instead.
func (*VMHealth) Descriptor() ([]byte, []int) {
	return file_proto_commands_proto_rawDescGZIP(), []int{8}
}

func (x *VMHealth) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *VMHealth) GetMemoryUsagePercent() float64 {
	if x != nil {
		return x.MemoryUsagePercent
	}
	return 0
}

func (x *VMHealth) GetDiskUsagePercent() float64 {
	if x != nil {
		return x.DiskUsagePercent
	}
	return 0
}

func (x *VMHealth) GetMemoryTotalBytes() int64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *VMHealth) GetMemoryUsedBytes() int64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *VMHealth) GetDiskTotalBytes() int64 {
	if x != nil {
		return x.DiskTotalBytes
	}
	return 0
}

func (x *VMHealth) GetDiskUsedBytes() int64 {
	if x != nil {
		return x.DiskUsedBytes
	}
	return 0
}

// RunnerState contains runner status
type RunnerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"` // idle, running, offline
	Configured    bool                   `protobuf:"varint,2,opt,name=configured,proto3" json:"configured,omitempty"`
	RunnerName    string                 `protobuf:"bytes,3,opt,name=runner_name,json=runnerName,proto3" json:"runner_name,omitempty"`
	Labels        []string               `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunnerState) Reset() {
	*x = RunnerState{}
	mi := &file_proto_commands_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunnerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunnerState) ProtoMessage() {}

func (x *RunnerState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commands_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunnerState.ProtoReflect.Descriptor instead.
func (*RunnerState) Descriptor() ([]byte, []int) {
	return file_proto_commands_proto_rawDescGZIP(), []int{9}
}

func (x *RunnerState) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *RunnerState) GetConfigured() bool {
	if x != nil {
		return x.Configured
	}
	return false
}

func (x *RunnerState) GetRunnerName() string {
	if x != nil {
		return x.RunnerName
	}
	return ""
}

func (x *RunnerState) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// JobInfo contains current job information
type JobInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Repository    string                 `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"`
	Branch        string                 `protobuf:"bytes,4,opt,name=branch,proto3" json:"branch,omitempty"`
	Commit        string                 `protobuf:"bytes,5,opt,name=commit,proto3" json:"commit,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // running, completed, failed
	StartedAt     int64                  `protobuf:"varint,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobInfo) Reset() {
	*x = JobInfo{}
	mi := &file_proto_commands_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobInfo) ProtoMessage() {}

func (x *JobInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commands_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobInfo.ProtoReflect.Descriptor instead.
func (*JobInfo) Descriptor() ([]byte, []int) {
	return file_proto_commands_proto_rawDescGZIP(), []int{10}
}

func (x *JobInfo) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobInfo) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *JobInfo) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *JobInfo) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *JobInfo) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *JobInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobInfo) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

// ErrorNotification represents errors from either side
type ErrorNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorNotification) Reset() {
	*x = ErrorNotification{}
	mi := &file_proto_commands_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorNotification) ProtoMessage() {}

func (x *ErrorNotification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commands_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorNotification.ProtoReflect.Descriptor instead.
func (*ErrorNotification) Descriptor() ([]byte, []int) {
	return file_proto_commands_proto_rawDescGZIP(), []int{11}
}

func (x *ErrorNotification) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorNotification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorNotification) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *ErrorNotification) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_commands_proto protoreflect.FileDescriptor

const file_proto_commands_proto_rawDesc = "" +
	"\n" +
	"\x14proto/commands.proto\x12\x0fmiglet.commands\"\xcb\x02\n" +
	"\rMIGletMessage\x12;\n" +
	"\aconnect\x18\x01 \x01(\v2\x1f.miglet.commands.ConnectRequestH\x00R\aconnect\x12>\n" +
	"\vcommand_ack\x18\x02 \x01(\v2\x1b.miglet.commands.CommandAckH\x00R\n" +
	"commandAck\x12:\n" +
	"\x05event\x18\x03 \x01(\v2\".miglet.commands.EventNotificationH\x00R\x05event\x12:\n" +
	"\theartbeat\x18\x04 \x01(\v2\x1a.miglet.commands.HeartbeatH\x00R\theartbeat\x12:\n" +
	"\x05error\x18\x05 \x01(\v2\".miglet.commands.ErrorNotificationH\x00R\x05errorB\t\n" +
	"\amessage\"\xd0\x01\n" +
	"\x11ControllerMessage\x12>\n" +
	"\vconnect_ack\x18\x01 \x01(\v2\x1b.miglet.commands.ConnectAckH\x00R\n" +
	"connectAck\x124\n" +
	"\acommand\x18\x02 \x01(\v2\x18.miglet.commands.CommandH\x00R\acommand\x12:\n" +
	"\x05error\x18\x03 \x01(\v2\".miglet.commands.ErrorNotificationH\x00R\x05errorB\t\n" +
	"\amessage\"o\n" +
	"\x0eConnectRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x17\n" +
	"\apool_id\x18\x02 \x01(\tR\x06poolId\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\tR\x05orgId\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"i\n" +
	"\n" +
	"ConnectAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0eserver_version\x18\x03 \x01(\tR\rserverVersion\"\x9e\x04\n" +
	"\aCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12O\n" +
	"\rstring_params\x18\x03 \x03(\v2*.miglet.commands.Command.StringParamsEntryR\fstringParams\x12F\n" +
	"\n" +
	"int_params\x18\x04 \x03(\v2'.miglet.commands.Command.IntParamsEntryR\tintParams\x12I\n" +
	"\vbool_params\x18\x05 \x03(\v2(.miglet.commands.Command.BoolParamsEntryR\n" +
	"boolParams\x12.\n" +
	"\x13string_array_params\x18\x06 \x03(\tR\x11stringArrayParams\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x1a?\n" +
	"\x11StringParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a<\n" +
	"\x0eIntParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a=\n" +
	"\x0fBoolParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\xdb\x01\n" +
	"\n" +
	"CommandAck\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12?\n" +
	"\x06result\x18\x04 \x03(\v2'.miglet.commands.CommandAck.ResultEntryR\x06result\x1a9\n" +
	"\vResultEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x85\x02\n" +
	"\x11EventNotification\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x13\n" +
	"\x05vm_id\x18\x02 \x01(\tR\x04vmId\x12\x17\n" +
	"\apool_id\x18\x03 \x01(\tR\x06poolId\x12\x15\n" +
	"\x06org_id\x18\x04 \x01(\tR\x05orgId\x12@\n" +
	"\x04data\x18\x05 \x03(\v2,.miglet.commands.EventNotification.DataEntryR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc0\x02\n" +
	"\tHeartbeat\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x17\n" +
	"\apool_id\x18\x02 \x01(\tR\x06poolId\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\tR\x05orgId\x121\n" +
	"\x06health\x18\x04 \x01(\v2\x19.miglet.commands.VMHealthR\x06health\x12?\n" +
	"\frunner_state\x18\x05 \x01(\v2\x1c.miglet.commands.RunnerStateR\vrunnerState\x129\n" +
	"\vcurrent_job\x18\x06 \x01(\v2\x18.miglet.commands.JobInfoR\n" +
	"currentJob\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12!\n" +
	"\fmiglet_state\x18\b \x01(\tR\vmigletState\"\xc2\x02\n" +
	"\bVMHealth\x12*\n" +
	"\x11cpu_usage_percent\x18\x01 \x01(\x01R\x0fcpuUsagePercent\x120\n" +
	"\x14memory_usage_percent\x18\x02 \x01(\x01R\x12memoryUsagePercent\x12,\n" +
	"\x12disk_usage_percent\x18\x03 \x01(\x01R\x10diskUsagePercent\x12,\n" +
	"\x12memory_total_bytes\x18\x04 \x01(\x03R\x10memoryTotalBytes\x12*\n" +
	"\x11memory_used_bytes\x18\x05 \x01(\x03R\x0fmemoryUsedBytes\x12(\n" +
	"\x10disk_total_bytes\x18\x06 \x01(\x03R\x0ediskTotalBytes\x12&\n" +
	"\x0fdisk_used_bytes\x18\a \x01(\x03R\rdiskUsedBytes\"|\n" +
	"\vRunnerState\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x1e\n" +
	"\n" +
	"configured\x18\x02 \x01(\bR\n" +
	"configured\x12\x1f\n" +
	"\vrunner_name\x18\x03 \x01(\tR\n" +
	"runnerName\x12\x16\n" +
	"\x06labels\x18\x04 \x03(\tR\x06labels\"\xbe\x01\n" +
	"\aJobInfo\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1e\n" +
	"\n" +
	"repository\x18\x03 \x01(\tR\n" +
	"repository\x12\x16\n" +
	"\x06branch\x18\x04 \x01(\tR\x06branch\x12\x16\n" +
	"\x06commit\x18\x05 \x01(\tR\x06commit\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"started_at\x18\a \x01(\x03R\tstartedAt\"\xe6\x01\n" +
	"\x11ErrorNotification\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12I\n" +
	"\adetails\x18\x03 \x03(\v2/.miglet.commands.ErrorNotification.DetailsEntryR\adetails\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012j\n" +
	"\x0eCommandService\x12X\n" +
	"\x0eStreamCommands\x12\x1e.miglet.commands.MIGletMessage\x1a\".miglet.commands.ControllerMessage(\x010\x01B)Z'github.com/monkci/miglet/proto/commandsb\x06proto3"

var (
	file_proto_commands_proto_rawDescOnce sync.Once
	file_proto_commands_proto_rawDescData []byte
)

func file_proto_commands_proto_rawDescGZIP() []byte {
	file_proto_commands_proto_rawDescOnce.Do(func() {
		file_proto_commands_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_commands_proto_rawDesc), len(file_proto_commands_proto_rawDesc)))
	})
	return file_proto_commands_proto_rawDescData
}

var file_proto_commands_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_commands_proto_goTypes = []any{
	(*MIGletMessage)(nil),     // 0: miglet.commands.MIGletMessage
	(*ControllerMessage)(nil), // 1: miglet.commands.ControllerMessage
	(*ConnectRequest)(nil),    // 2: miglet.commands.ConnectRequest
	(*ConnectAck)(nil),        // 3: miglet.commands.ConnectAck
	(*Command)(nil),           // 4: miglet.commands.Command
	(*CommandAck)(nil),        // 5: miglet.commands.CommandAck
	(*EventNotification)(nil), // 6: miglet.commands.EventNotification
	(*Heartbeat)(nil),         // 7: miglet.commands.Heartbeat
	(*VMHealth)(nil),          // 8: miglet.commands.VMHealth
	(*RunnerState)(nil),       // 9: miglet.commands.RunnerState
	(*JobInfo)(nil),           // 10: miglet.commands.JobInfo
	(*ErrorNotification)(nil), // 11: miglet.commands.ErrorNotification
	nil,                       // 12: miglet.commands.Command.StringParamsEntry
	nil,                       // 13: miglet.commands.Command.IntParamsEntry
	nil,                       // 14: miglet.commands.Command.BoolParamsEntry
	nil,                       // 15: miglet.commands.CommandAck.ResultEntry
	nil,                       // 16: miglet.commands.EventNotification.DataEntry
	nil,                       // 17: miglet.commands.ErrorNotification.DetailsEntry
}
var file_proto_commands_proto_depIdxs = []int32{
	2,  // 0: miglet.commands.MIGletMessage.connect:type_name -> miglet.commands.ConnectRequest
	5,  // 1: miglet.commands.MIGletMessage.command_ack:type_name -> miglet.commands.CommandAck
	6,  // 2: miglet.commands.MIGletMessage.event:type_name -> miglet.commands.EventNotification
	7,  // 3: miglet.commands.MIGletMessage.heartbeat:type_name -> miglet.commands.Heartbeat
	11, // 4: miglet.commands.MIGletMessage.error:type_name -> miglet.commands.ErrorNotification
	3,  // 5: miglet.commands.ControllerMessage.connect_ack:type_name -> miglet.commands.ConnectAck
	4,  // 6: miglet.commands.ControllerMessage.command:type_name -> miglet.commands.Command
	11, // 7: miglet.commands.ControllerMessage.error:type_name -> miglet.commands.ErrorNotification
	12, // 8: miglet.commands.Command.string_params:type_name -> miglet.commands.Command.StringParamsEntry
	13, // 9: miglet.commands.Command.int_params:type_name -> miglet.commands.Command.IntParamsEntry
	14, // 10: miglet.commands.Command.bool_params:type_name -> miglet.commands.Command.BoolParamsEntry
	15, // 11: miglet.commands.CommandAck.result:type_name -> miglet.commands.CommandAck.ResultEntry
	16, // 12: miglet.commands.EventNotification.data:type_name -> miglet.commands.EventNotification.DataEntry
	8,  // 13: miglet.commands.Heartbeat.health:type_name -> miglet.commands.VMHealth
	9,  // 14: miglet.commands.Heartbeat.runner_state:type_name -> miglet.commands.RunnerState
	10, // 15: miglet.commands.Heartbeat.current_job:type_name -> miglet.commands.JobInfo
	17, // 16: miglet.commands.ErrorNotification.details:type_name -> miglet.commands.ErrorNotification.DetailsEntry
	0,  // 17: miglet.commands.CommandService.StreamCommands:input_type -> miglet.commands.MIGletMessage
	1,  // 18: miglet.commands.CommandService.StreamCommands:output_type -> miglet.commands.ControllerMessage
	18, // [18:19] is the sub-list for method output_type
	17, // [17:18] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_proto_commands_proto_init() }
func file_proto_commands_proto_init() {
	if File_proto_commands_proto != nil {
		return
	}
	file_proto_commands_proto_msgTypes[0].OneofWrappers = []any{
		(*MIGletMessage_Connect)(nil),
		(*MIGletMessage_CommandAck)(nil),
		(*MIGletMessage_Event)(nil),
		(*MIGletMessage_Heartbeat)(nil),
		(*MIGletMessage_Error)(nil),
	}
	file_proto_commands_proto_msgTypes[1].OneofWrappers = []any{
		(*ControllerMessage_ConnectAck)(nil),
		(*ControllerMessage_Command)(nil),
		(*ControllerMessage_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_commands_proto_rawDesc), len(file_proto_commands_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_commands_proto_goTypes,
		DependencyIndexes: file_proto_commands_proto_depIdxs,
		MessageInfos:      file_proto_commands_proto_msgTypes,
	}.Build()
	File_proto_commands_proto = out.File
	file_proto_commands_proto_goTypes = nil
	file_proto_commands_proto_depIdxs = nil
}
